name: techcon2022
description: Full-stack Dart demo project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  material_color_generator: ^1.1.0
  amplify_auth_cognito: ^0.6.9
  amplify_flutter: ^0.6.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  image_path: assets/icon/icon.png
  ios: true
